src/Entity/Sales.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SalesRepository")
 */
class Sales
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="sales")
     */
    private $item_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $order_qty;

    /**
     * @ORM\Column(type="integer")
     */
    private $batch_sequence;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $cost_price;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $sell_price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getItemId(): ?Product
    {
        return $this->item_id;
    }

    public function setItemId(?Product $item_id): self
    {
        $this->item_id = $item_id;

        return $this;
    }

    public function getOrderQty(): ?int
    {
        return $this->order_qty;
    }

    public function setOrderQty(int $order_qty): self
    {
        $this->order_qty = $order_qty;

        return $this;
    }

    public function getBatchSequence(): ?int
    {
        return $this->batch_sequence;
    }

    public function setBatchSequence(int $batch_sequence): self
    {
        $this->batch_sequence = $batch_sequence;

        return $this;
    }

    public function getCostPrice(): ?string
    {
        return $this->cost_price;
    }

    public function setCostPrice(string $cost_price): self
    {
        $this->cost_price = $cost_price;

        return $this;
    }

    public function getSellPrice(): ?string
    {
        return $this->sell_price;
    }

    public function setSellPrice(string $sell_price): self
    {
        $this->sell_price = $sell_price;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/SalesType.php
<?php

namespace App\Form;

use App\Entity\Sales;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class SalesType
 * @package App\Form
 */
class SalesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('order_qty')
            ->add('sell_price')
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sales::class,
        ]);
    }
}

src/Controller/SalesController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Sales;
use App\Form\SalesType;
use App\Repository\SalesRepository;
use App\Service\FifoProductSalesService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/sales")
 */
class SalesController extends AbstractController
{
    /**
     * @Route("/", name="sales_index", methods={"GET"})
     * @param SalesRepository $salesRepository
     * @return Response
     */
    public function index(SalesRepository $salesRepository): Response
    {
        return $this->render('sales/index.html.twig', [
            'sales' => $salesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="sales_new", methods={"GET","POST"})
     * @param Request $request
     * @param FifoProductSalesService $fifoProductSalesService
     * @return Response
     */
    public function new(Request $request, FifoProductSalesService $fifoProductSalesService): Response
    {
        $sale = new Sales();
        $form = $this->createForm(SalesType::class, $sale);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $postSales = $request->request->get('sales');
            $productsAsFifo = $fifoProductSalesService->getFifoItem($postSales);

            foreach ($productsAsFifo as $item){
                $sale = new Sales();
                $sale->setItemId($this->getDoctrine()->getRepository(Product::class)->find($item['item_id']));
                $sale->setOrderQty($item['order_qty']);
                $sale->setBatchSequence($item['batch_sequence']);
                $sale->setCostPrice($item['cost_price']);
                $sale->setSellPrice($postSales['sell_price']);
                $entityManager->persist($sale);
            }
            $entityManager->flush();
            return $this->redirectToRoute('sales_index');
        }

        return $this->render('sales/new.html.twig', [
            'sale' => $sale,
            'form' => $form->createView(),
        ]);
    }

}

templates/sales/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/sales/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sales index{% endblock %}

{% block body %}
    <h1>Sales index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Order_qty</th>
                <th>Batch_sequence</th>
                <th>Cost_price</th>
                <th>Sell_price</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        {% for sale in sales %}
            <tr>
                <td>{{ sale.id }}</td>
                <td>{{ sale.orderQty }}</td>
                <td>{{ sale.batchSequence }}</td>
                <td>{{ sale.costPrice }}</td>
                <td>{{ sale.sellPrice }}</td>
                <td>{{ sale.date ? sale.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('sales_new') }}" class="btn btn-info" >Create new</a>
{% endblock %}

templates/sales/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Sales{% endblock %}

{% block body %}
    <h4>New Sell</h4>

    {{ include('sales/_form.html.twig') }}

    <a href="{{ path('sales_index') }}" class="btn btn-dark">List of Sales</a>
{% endblock %}